const T={
zh:{guide:'客房數位指南',hero:'住宿期間需要的資訊，整理成清楚、好操作的數位服務。此版本為通用 DEMO，不含任何真實飯店營運資料。',menu:'服務選單',choose:'請選擇您需要的服務',home:'首頁',stay:'住宿指南',staySub:'住宿規範與安全資訊',room:'客房設備',roomSub:'房內設備與備品',tv:'電視娛樂',tvSub:'操作說明與頻道',policies:'館內規範',policiesSub:'禁菸、環保與安全',dining:'餐飲・交通',diningSub:'早餐與交通方式',services:'旅客服務',servicesSub:'活動與聯絡方式',back:'返回',campaignTitle:'本月旅客小禮',campaignText:'此區為活動彈窗示範，可替換成飯店當期 DM、連結與活動內容。',understand:'我知道了'},
en:{guide:'Digital Guest Guide',hero:'Essential stay information in a clear digital experience. This is a reusable demo with no real hotel operational data.',menu:'Services',choose:'Choose what you need',home:'Home',stay:'Stay Guide',staySub:'Rules and safety',room:'Room Equipment',roomSub:'Facilities and amenities',tv:'TV & Entertainment',tvSub:'Controls and channels',policies:'Hotel Policies',policiesSub:'Smoking, sustainability and safety',dining:'Dining & Transport',diningSub:'Breakfast and transportation',services:'Guest Services',servicesSub:'Campaigns and contact',back:'Back',campaignTitle:'Guest Gift Demo',campaignText:'Demo campaign modal. Replace with the hotel’s current artwork, link and campaign content.',understand:'Got it'},
ja:{guide:'デジタルゲストガイド',hero:'滞在中に必要な情報を分かりやすくまとめたデモ版です。実在ホテルの運営情報は含まれていません。',menu:'サービス',choose:'必要な項目を選択してください',home:'ホーム',stay:'宿泊ガイド',staySub:'規則・安全情報',room:'客室設備',roomSub:'設備・アメニティ',tv:'テレビ',tvSub:'操作・チャンネル',policies:'館内規則',policiesSub:'禁煙・環境・安全',dining:'食事・交通',diningSub:'朝食・交通案内',services:'ゲストサービス',servicesSub:'キャンペーン・連絡先',back:'戻る',campaignTitle:'ゲストギフト DEMO',campaignText:'キャンペーン用ポップアップのデモです。',understand:'確認'},
ko:{guide:'디지털 객실 안내',hero:'투숙 중 필요한 정보를 간결하게 정리한 재사용 가능한 데모입니다. 실제 호텔 운영 정보는 포함하지 않습니다.',menu:'서비스',choose:'필요한 서비스를 선택하세요',home:'홈',stay:'숙박 안내',staySub:'규정 및 안전 정보',room:'객실 시설',roomSub:'시설 및 비품',tv:'TV',tvSub:'사용법 및 채널',policies:'호텔 규정',policiesSub:'금연·환경·안전',dining:'식사·교통',diningSub:'조식 및 교통',services:'고객 서비스',servicesSub:'이벤트 및 연락',back:'뒤로',campaignTitle:'고객 선물 DEMO',campaignText:'이벤트 팝업 데모입니다.',understand:'확인'}
};
let lang='zh',current='home';
const cards=[['stay','⌂'],['room','▣'],['tv','▻'],['policies','◇'],['dining','♢'],['services','✦']];
const detail={stay:['入住／退房時間可由導入飯店自行設定。','住宿規範、消防逃生與緊急聯絡資訊可分層呈現。','此 DEMO 不含任何真實旅客或內部資料。'],room:['免費 Wi‑Fi','空調','冰箱','快煮壺','電視','吹風機','淋浴設備'],tv:['Step 01　開啟電視與機上盒','Step 02　選擇正確訊號來源','Step 03　等待畫面載入；頻道表可由資料檔維護'],policies:['全館禁菸政策範例','一次性備品與永續政策範例','損壞／遺失費用應由各飯店自行設定'],dining:['早餐：07:00–10:00（DEMO）','最近車站：步行約 8 分鐘（DEMO）','機場：車程約 30 分鐘（DEMO）'],services:['櫃檯：請按客房電話 9（DEMO）','活動彈窗可獨立更新，不需改動主頁架構','可串接官網、評論、地圖或其他服務連結']};
function tr(k){return T[lang][k]||T.zh[k]||k}
function apply(){document.documentElement.lang=lang==='zh'?'zh-Hant':lang;document.querySelectorAll('[data-k]').forEach(e=>e.textContent=tr(e.dataset.k));}
function home(){return `<section class="hero"><div class="eyebrow">AURORA DIGITAL CONCIERGE · DEMO</div><h1 data-k="guide">${tr('guide')}</h1><p data-k="hero">${tr('hero')}</p><div class="demo-note">SANITIZED DEMO · Generic sample content only</div></section><section class="section"><div class="section-head"><h2 data-k="menu">${tr('menu')}</h2><p data-k="choose">${tr('choose')}</p></div><div class="grid">${cards.map(([k,i])=>`<button class="card" onclick="go('${k}')"><span class="icon">${i}</span><span class="arrow">↗</span><h3 data-k="${k}">${tr(k)}</h3><p data-k="${k}Sub">${tr(k+'Sub')}</p></button>`).join('')}</div></section>`}
function page(k){const tags=k==='room'?detail[k].map(x=>`<span class="tag">${x}</span>`).join(''):'';const list=k==='room'?'':`<ul>${detail[k].map(x=>`<li>${x}</li>`).join('')}</ul>`;return `<section class="section"><div class="pagebar"><button class="back" onclick="go('home')">← <span data-k="back">${tr('back')}</span></button></div><div class="detail"><div class="eyebrow">DEMO MODULE</div><h2 data-k="${k}">${tr(k)}</h2><p data-k="${k}Sub">${tr(k+'Sub')}</p><div class="demo-note">以下皆為展示資料，正式導入時由客戶內容取代。</div>${tags}${list}${k==='services'?'<p><button class="primary" onclick="openModal()">Campaign popup demo</button></p>':''}</div></section>`}
function go(k){current=k;document.getElementById('app').innerHTML=k==='home'?home():page(k);document.getElementById('bottom').style.display=k==='home'?'none':'flex';apply();scrollTo(0,0)}
function openModal(){document.getElementById('modal').hidden=false;apply()}function closeModal(){document.getElementById('modal').hidden=true}
document.getElementById('lang').addEventListener('change',e=>{lang=e.target.value;go(current)});go('home');setTimeout(()=>{if(!sessionStorage.getItem('demoSeen')){sessionStorage.setItem('demoSeen','1');openModal()}},1400);